### PR TITLE
Add kotlinter

### PR DESCRIPTION
**Pull request by dessalines**
This lints / formats the code to a common standard, using kotlinter with its defaults. You can run either

`./gradlew lintKotlin`
`./gradlew formatKotlin`

Its best to run the former in your CI pipeline, but I'm not sure what you're using.

### CODE REVIEW

**Comment by dessalines** [comment]
Btw, you can jast cherry pick the commit that adds support, and run `./gradlew formatKotlin` on your own.

**Comment by dessalines** [comment]
bump @alorma , I can do a PR just to add kotlinter, and not do the formatting if you like.

**Comment by alorma** [comment]
Sure, let's see

**Comment by dessalines** [comment]
Okay its updated. After this is merged, you can run `./gradlew formatKotlin` on the codebase.

**Review by alorma — COMMENTED** [review]
Ok, so how should I run it on the project?

**Comment by dessalines** [comment]
Run `./gradlew formatKotlin`

**Comment by alorma** [comment]
Thanks, I will run that some day soon.

**Comment by dessalines** [comment]
It's also a good idea to add `./gradlew lintKotlin` to your CI at some point.

**Pull request merged**
