### PR TITLE
Feature: New SettingsSlider item

### PR DESCRIPTION
**Pull request by serbelga**
New `SettingsSlider` item

https://user-images.githubusercontent.com/26246782/134224860-fbe3ae17-3c98-47fb-bbfb-add0f13aa1ec.mp4

### CODE REVIEW

**Comment by alorma** [comment]
Hi @serbelga !

Any news on this code change? It looks so great addition for this library

**Comment by serbelga** [comment]
> Hi @serbelga !
> 
> Any news on this code change? It looks so great addition for this library

Yes, I'd like to finish the development of this feature this week

**Comment by serbelga** [comment]
> Hi @serbelga !
> 
> Any news on this code change? It looks so great addition for this library

I've just done some update on SettingsSlider item

**Review by alorma — APPROVED** [review]
It looks so cool!

**Comment by alorma** [comment]
Thanks @serbelga . I will cleanup some code of datastore as it's not really ready for production and will publish a new version of the lib!

**Comment by alorma** [comment]
@serbelga Released version 0.4.0 with slider setting tile

**Pull request merged**
