### PR TITLE
Enhancements & fixes.

### PR DESCRIPTION
**Pull request by ItzNotABug**
This PR includes following enhancements, fixes:
1. `OnItemSelected` & `OnItemsSelected` for both m2 & m3 variants via 63e5670 & 8e24215.
Current implementation does not allow the developer to know which items were selected without explicitly using the `SharedPreference` or observing the `remember*SettingState` somewhere in the composable.

2. The `SettingsTileIcon` leaves an empty space if the `icon` is null which is not correct as per the native preferences & also the m3's `SettingsTileScaffold` implementation which uses a `ListItem` & therefore has an `.padding(end = 16.dp)` for the `leading` content.

3. The same commit as pointer **2** includes fixes to Checkbox & Switch layout positions.
These widgets should be to the far right/end of the tile in `m2`.
The `m3` has correct implementation due to `ListItem.trailingContent`.

4. Currently if the **same** item is selected in a `SettingsList` then the `AlertDialog` is not dismissed which does not seem to be the right behaviour. An `AlertDialog` should be dismissed on any confirmation action.

**Note**: I'm not 100% sure that the `padding` I've applied to both `Checkbox` & `Switch` widgets i.e. `padding(end = 8.dp)` is correct as per guidelines, I did not have the chance to look at the docs but they looked similar to the tile icon's start/end padding.

### CODE REVIEW

**Review by alorma — APPROVED** [review]

**Comment by alorma** [comment]
Thanks! I will release a version later!

BTW: are you using it on an app? Would you share screenshots? I would love to see the library applied! (Privately if you want)

**Comment by ItzNotABug** [comment]
Sure thing!
I'll keep an eye on the releases.

I'm currently trying to add compose preferences to this project (nothing fancy though):
https://github.com/ItzNotABug/AIR

**Comment by alorma** [comment]
Released!

**Comment by ItzNotABug** [comment]
> Released!

Is `0.21.0` released on mavenCentral?

**Comment by alorma** [comment]
> Is `0.21.0` released on mavenCentral?

Yes, It failed and I got no notification about it... check now

**Pull request merged**
